"""render_v3 SELF-FORCING (DAgger / scheduled-sampling) fine-tune.

This is train_render_v3.py with ONE conceptual change to the training loop:

  Teacher-forced base trains the prev-frame branch on the CLEAN GT previous
  frame (prev[:,:,1:] = x0[:,:,:-1]).  At inference (validate_v3 ar=True) the
  prev frame is the model's OWN noisy prediction -> train/test mismatch ->
  autoregressive drift.

  Self-forcing fixes this with DAgger: with probability sf_prob (ramped from 0
  to sf_prob_hi over phase_steps) a step CONDITIONS on the model's OWN previously
  predicted frames (generated by a CHEAP, DETACHED autoregressive ODE rollout,
  exactly the validate_v3 ar pattern) instead of the GT-shifted prev, while the
  graded flow/tc/pc losses STILL supervise toward the GROUND-TRUTH x0.  So the
  model learns to recover from its own conditioning errors.

Everything else (CondEncoderV3, FlowVNetV3, make_cond_v3, rectified-flow
convention, tc + pc losses, grad-ckpt, DDP, bf16 autocast, checkpoint meta) is
IDENTICAL to the base.  Checkpoints go to a SEPARATE dir / names (v3sf_*) so the
base checkpoints are never touched, and carry the SAME meta keys so validate_v3
can load them.

--resume (REQUIRED) warm-starts from a v3 BASE ckpt.  If a v3sf_latest.pt already
exists in --ckpt_dir, that SF checkpoint is resumed instead (self-resume).
"""
from __future__ import annotations
import argparse, os, sys, time, math
from datetime import datetime
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torch.distributed as dist

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from voxel_dataset import VoxelDiTDataset
from vae_3d import VAE3D
from renderer_explicit import (voxel_to_compact_grids, LAT_TO_SRC,
                               EYE_CENTER, EYE_HEIGHT,
                               RGB_T, RGB_C, RGB_H, RGB_W, N_COMPACT)
from renderer_flow import (timestep_embedding, AdaGNBlock, _exact_eye)
from raster_torch import MAX_DEPTH
from raster_peel import rasterize_peel

# Reuse the model + cond + loss building blocks from the base trainer verbatim,
# so SF can never silently diverge from the base architecture / forward.
import train_render_v3 as T3
from train_render_v3 import (CondEncoderV3, FlowVNetV3, make_cond_v3,
                             PerceptualLoss, load_wan, warm_start,
                             is_dist, rank0, log)

USE_RASTER = os.environ.get('USE_RASTER', '1') == '1'


# ===========================================================================
# Self-forcing prev-frame generator.
#   Detached (torch.no_grad), cheap (sf_ode_steps) autoregressive ODE rollout,
#   reusing validate_v3's v3_render(ar=True) logic EXACTLY: frame-by-frame,
#   prev = own previous CLEAN prediction, frame0 -> zero prev + first token.
#   Returns x0_pred_own (B, RGB_C, T, H, W).  This is the model's own predicted
#   CLEAN frames; we will then shift it to build the conditioning prev tensor.
# ===========================================================================
@torch.no_grad()
def selfforce_prev(vnet, cond, B, T, H, W, dev, n_ode):
    """Generate the model's OWN clean frame predictions autoregressively.

    cond: (B, cond_ch, T, H, W) already windowed to T frames.
    Mirrors validate_v3.v3_render(ar=True). Fully detached.
    """
    # eval-mode forward so grad_ckpt / dropout-style paths are inactive and no
    # graph is built; restore train mode afterwards.
    was_training = vnet.training
    vnet.eval()
    taus = torch.linspace(1.0, 0.0, n_ode + 1, device=dev)
    preds = []  # each (B, RGB_C, 1, H, W)
    for t in range(T):
        ct = cond[:, :, t:t + 1]
        if t == 0:
            prev = torch.zeros(B, RGB_C, 1, H, W, device=dev)
            fm = torch.ones(B, 1, dtype=torch.bool, device=dev)
        else:
            prev = preds[-1]
            fm = torch.zeros(B, 1, dtype=torch.bool, device=dev)
        x = torch.randn(B, RGB_C, 1, H, W, device=dev)
        for i in range(n_ode):
            tv = torch.full((B,), float(taus[i]), device=dev)
            with torch.cuda.amp.autocast(dtype=torch.bfloat16):
                v = vnet(x, tv, ct, prev, fm)
            # rectified-flow Euler: x_{tau-} = x - (dtau) * v  (taus descend 1->0)
            x = x - (taus[i] - taus[i + 1]) * v.float()
        preds.append(x)            # x is the model's predicted CLEAN frame at tau=0
    return torch.cat(preds, dim=2)  # (B, RGB_C, T, H, W)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--steps", type=int, default=20000)
    ap.add_argument("--batch", type=int, default=4)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--warmup", type=int, default=200)
    ap.add_argument("--rast", type=int, default=96)
    ap.add_argument("--base", type=int, default=160)
    ap.add_argument("--cond_base", type=int, default=96)
    ap.add_argument("--cond_ch", type=int, default=64)
    ap.add_argument("--peel_k", type=int, default=2)
    ap.add_argument("--clip_frames", type=int, default=9, help="latent frames per clip (<=9)")
    ap.add_argument("--w_temporal", type=float, default=0.1)
    ap.add_argument("--w_percep", type=float, default=0.05)
    ap.add_argument("--percep_frames", type=int, default=2)
    # ---- self-forcing knobs ----
    ap.add_argument("--sf_prob_hi", type=float, default=0.5,
                    help="max probability a step is self-forced (end of ramp)")
    ap.add_argument("--phase_steps", type=int, default=4000,
                    help="steps over which sf_prob ramps 0 -> sf_prob_hi linearly")
    ap.add_argument("--sf_ode_steps", type=int, default=12,
                    help="cheap detached ODE depth for generating own-pred prev frames")
    # ---- plumbing ----
    ap.add_argument("--log_every", type=int, default=25)
    ap.add_argument("--ckpt_min", type=float, default=20.0, help="rolling ckpt cadence (min)")
    ap.add_argument("--keep_every", type=int, default=2000, help="keep a PERMANENT ckpt every N steps")
    ap.add_argument("--num_workers", type=int, default=6)
    ap.add_argument("--ckpt_dir", type=str, default="/home/flukol/render_v2_treechop/ckpt_v3sf")
    ap.add_argument("--resume", type=str, required=True,
                    help="REQUIRED: v3 BASE ckpt to warm-start from (self-resumes v3sf_latest.pt if present)")
    ap.add_argument("--grad_ckpt", action="store_true")
    ap.add_argument("--no_percep", action="store_true")
    ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()

    # ---- distributed (torchrun --standalone) ----
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    world = int(os.environ.get("WORLD_SIZE", 1))
    if world > 1:
        dist.init_process_group("nccl")
        torch.cuda.set_device(local_rank)
    dev = torch.device("cuda", local_rank)

    RAST_H = (args.rast // 4) * 4
    RAST_W = (int(round(RAST_H * 16 / 9)) // 4) * 4
    K = args.peel_k
    log(f"[SF] RAST {RAST_H}x{RAST_W}  peel_K={K}  clip_frames={args.clip_frames}  world={world}")
    log(f"[SF] sf_prob_hi={args.sf_prob_hi} phase_steps={args.phase_steps} sf_ode_steps={args.sf_ode_steps}")
    if rank0():
        os.makedirs(args.ckpt_dir, exist_ok=True)

    VOX_VAE = os.environ.get("VOX_VAE", "/home/flukol/v12/code/vae_final.pt")
    VOX_VOCAB = os.environ.get("VOX_VOCAB", "/home/flukol/v12/code/voxel_vocab.npz")
    vae = VAE3D(num_classes=2021, latent_channels=48, middle_channels=(32, 128, 512))
    sd = torch.load(VOX_VAE, map_location="cpu")
    sd = sd.get("model", sd.get("state_dict", sd))
    vae.load_state_dict({k.replace("module.", ""): v for k, v in sd.items()}, strict=False)
    vae = vae.to(dev).eval()
    for p in vae.parameters():
        p.requires_grad_(False)
    vv = np.load(VOX_VOCAB)
    id2compact = torch.from_numpy(vv["id2compact"]).long().to(dev)

    cond_enc = CondEncoderV3(base=args.cond_base, cond_ch=args.cond_ch, K=K).to(dev)
    vnet = FlowVNetV3(cond_ch=args.cond_ch, base=args.base, grad_ckpt=args.grad_ckpt).to(dev)
    nparams = sum(p.numel() for p in vnet.parameters()) + sum(p.numel() for p in cond_enc.parameters())
    log(f"[SF] flow params: {nparams/1e6:.2f}M")

    # ---- resume / warm-start ----
    # Priority: self-resume v3sf_latest.pt (own progress) > warm-start from BASE.
    start_step = 0
    params = list(vnet.parameters()) + list(cond_enc.parameters())
    opt = torch.optim.AdamW(params, lr=args.lr, betas=(0.9, 0.95), weight_decay=0.0)
    latest_sf = os.path.join(args.ckpt_dir, "v3sf_latest.pt")
    if os.path.exists(latest_sf):
        ck = torch.load(latest_sf, map_location="cpu")
        cond_enc.load_state_dict(ck["cond_enc"]); vnet.load_state_dict(ck["vnet"])
        if "opt" in ck:
            opt.load_state_dict(ck["opt"])
        start_step = ck.get("step", 0)
        log(f"[SF] RESUMED self-forcing ckpt {latest_sf} @ {start_step}")
    elif args.resume and os.path.exists(args.resume):
        start_step = 0  # warm-start = fresh schedule (sf ramp begins at this step)
        warm_start(cond_enc, vnet, args.resume)
        log(f"[SF] warm-started from BASE ckpt {args.resume}; sf ramp starts now")
    else:
        raise FileNotFoundError(
            f"--resume base ckpt required and not found: {args.resume!r} "
            f"(and no {latest_sf})")
    sf_start = start_step  # the step at which the sf_prob ramp is anchored

    # ---- DDP wrap ----
    if world > 1:
        cond_enc = nn.parallel.DistributedDataParallel(cond_enc, device_ids=[local_rank])
        vnet = nn.parallel.DistributedDataParallel(vnet, device_ids=[local_rank],
                                                   find_unused_parameters=False)
    # underlying vnet module (for the detached eval-mode SF rollout)
    vnet_core = vnet.module if world > 1 else vnet

    # ---- perceptual ----
    percep = None; wan = None
    if not args.no_percep and args.w_percep > 0:
        percep = PerceptualLoss(dev).to(dev)
        wan = load_wan(dev)
        if wan is None:
            percep = None
            log("[SF][perceptual] disabled (no Wan VAE)")

    # ---- data ----
    ds = VoxelDiTDataset(clip_len=33, require_rgb=True, require_clip=False,
                         require_clip_pf=False, clip_dir=None, clip_pf_dir=None,
                         samples_per_epoch=400000, samples_per_episode=1)
    log(f"[SF] valid episodes: {len(ds.index)}")
    sampler = None
    if world > 1:
        sampler = torch.utils.data.distributed.DistributedSampler(ds, shuffle=True, drop_last=True)
    loader = DataLoader(ds, batch_size=args.batch, num_workers=args.num_workers,
                        drop_last=True, pin_memory=True, sampler=sampler,
                        shuffle=(sampler is None),
                        persistent_workers=args.num_workers > 0)

    it = iter(loader)
    t0 = time.time(); ema = None; last_ckpt = time.time()
    n_steps = 12 if args.smoke else args.steps
    Tf = min(args.clip_frames, RGB_T)
    n_sf_fired = 0

    for step in range(start_step, start_step + n_steps):
        try:
            b = next(it)
        except StopIteration:
            it = iter(loader); b = next(it)
        vox = b["voxel_lat"].to(dev, non_blocking=True)
        cam = b["camera"].to(dev, non_blocking=True)
        raw_cam = b["raw_camera"].to(dev, non_blocking=True) if "raw_camera" in b else None
        x0_full = b["rgb_lat"].to(dev, non_blocking=True).float()
        B = vox.shape[0]

        cond, hit, static = make_cond_v3(cond_enc, vae, id2compact, vox, cam, dev,
                                         RAST_H, RAST_W, K, raw_cam=raw_cam)
        x0 = x0_full[:, :, :Tf]
        cond = cond[:, :, :Tf]
        static = static[:, :, :Tf - 1]
        _, _, _, H, W = x0.shape

        # ---- scheduled-sampling decision ----
        sf_prob = min(1.0, (step - sf_start) / max(1, args.phase_steps)) * args.sf_prob_hi
        # one shared coin for the whole (DDP-synced) batch so all ranks agree
        is_sf = bool(torch.rand(1, device=dev).item() < sf_prob)

        first_mask = torch.zeros(B, Tf, dtype=torch.bool, device=dev)
        first_mask[:, 0] = True

        if is_sf:
            # DAgger: condition on the model's OWN previous predicted frames.
            # Detached, cheap ODE rollout -> own clean frame preds (B,RGB_C,Tf,H,W).
            x0_pred_own = selfforce_prev(vnet_core, cond, B, Tf, H, W, dev, args.sf_ode_steps)
            vnet.train()  # restore train mode after eval-mode rollout
            prev = torch.zeros_like(x0)
            prev[:, :, 1:] = x0_pred_own[:, :, :-1].detach()  # shift; detach belt-and-suspenders
            n_sf_fired += 1
        else:
            # teacher-forced: prev[t] = clean GT x0[t-1]  (identical to base)
            prev = torch.zeros_like(x0)
            prev[:, :, 1:] = x0[:, :, :-1]

        lr = args.lr * min(1.0, (step + 1 - start_step) / max(1, args.warmup))
        for pg in opt.param_groups:
            pg["lr"] = lr

        # ---- graded forward + rectified-flow loss (UNCHANGED, supervises toward GT) ----
        x1 = torch.randn_like(x0)
        tau = torch.rand(B, device=dev)
        tv = tau.view(B, 1, 1, 1, 1)
        x_tau = (1 - tv) * x0 + tv * x1
        v_target = x1 - x0

        with torch.cuda.amp.autocast(dtype=torch.bfloat16):
            v_pred = vnet(x_tau, tau, cond, prev, first_mask)
            flow_loss = F.mse_loss(v_pred.float(), v_target)
            x0_pred = (x_tau - tv * v_pred).float()
            dpred = (x0_pred[:, :, 1:] - x0_pred[:, :, :-1]).abs()
            tc_loss = (dpred * static).sum() / (static.sum() * RGB_C + 1e-6)
            loss = flow_loss + args.w_temporal * tc_loss

        pc_loss_val = 0.0
        if percep is not None:
            nf = min(args.percep_frames, Tf)
            idxs = torch.linspace(0, Tf - 1, nf).long()
            pl = x0_pred[:, :, idxs]
            gl = x0[:, :, idxs]
            with torch.no_grad():
                gt_rgb = wan.model.decode(gl.detach().float(), wan.scale).float()
            pred_rgb = wan.model.decode(pl.float(), wan.scale).float()
            pr = pred_rgb.permute(0, 2, 1, 3, 4).reshape(-1, 3, *pred_rgb.shape[-2:])
            gr = gt_rgb.permute(0, 2, 1, 3, 4).reshape(-1, 3, *gt_rgb.shape[-2:])
            pc_loss = percep(pr, gr.detach())
            loss = loss + args.w_percep * pc_loss
            pc_loss_val = pc_loss.item()

        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(params, 1.0)
        opt.step()

        l = loss.item(); ema = l if ema is None else 0.98 * ema + 0.02 * l
        if step % args.log_every == 0 or args.smoke:
            sps = (step + 1 - start_step) / (time.time() - t0)
            log(f"[SF] step {step} {'SELF-FORCED' if is_sf else 'teacher-forced'} "
                f"sf_prob {sf_prob:.3f} | loss {l:.4f} ema {ema:.4f} | flow {flow_loss.item():.4f} "
                f"tc {tc_loss.item():.4f} pc {pc_loss_val:.4f} | static% {static.mean().item():.2f} "
                f"hit% {hit[:, :, 0].float().mean().item():.2f} {sps:.2f} it/s "
                f"vstd {v_pred.float().std():.3f} | sf_fired {n_sf_fired}")

        # ---- checkpointing: SEPARATE dir + names (v3sf_*); base never overwritten ----
        if rank0() and not args.smoke:
            now = time.time()
            ce_sd = (cond_enc.module if world > 1 else cond_enc).state_dict()
            vn_sd = (vnet.module if world > 1 else vnet).state_dict()
            meta = {"step": step + 1, "vnet": vn_sd, "cond_enc": ce_sd, "opt": opt.state_dict(),
                    "rast_h": RAST_H, "rast_w": RAST_W, "cond_ch": args.cond_ch,
                    "base": args.base, "cond_base": args.cond_base, "peel_k": K,
                    "clip_frames": args.clip_frames}
            if (now - last_ckpt) > args.ckpt_min * 60:
                torch.save(meta, latest_sf); last_ckpt = now
                log(f"[SF]   rolling ckpt @ {step+1}")
            if (step + 1) % args.keep_every == 0:
                kp = os.path.join(args.ckpt_dir, f"v3sf_step{step+1}.pt")
                torch.save(meta, kp); last_ckpt = now
                log(f"[SF]   PERMANENT ckpt -> {kp}")

    # ---- smoke: still prove a checkpoint CAN be written (to the smoke dir) ----
    if rank0():
        ce_sd = (cond_enc.module if world > 1 else cond_enc).state_dict()
        vn_sd = (vnet.module if world > 1 else vnet).state_dict()
        final_meta = {"step": start_step + n_steps, "vnet": vn_sd, "cond_enc": ce_sd,
                      "opt": opt.state_dict(), "rast_h": RAST_H, "rast_w": RAST_W,
                      "cond_ch": args.cond_ch, "base": args.base, "cond_base": args.cond_base,
                      "peel_k": K, "clip_frames": args.clip_frames}
        torch.save(final_meta, os.path.join(args.ckpt_dir, "v3sf_final.pt"))
        log(f"[SF] wrote v3sf_final.pt to {args.ckpt_dir}")
    log(f"[SF] TRAINING DONE  (self-forced steps fired: {n_sf_fired}/{n_steps})")
    if world > 1:
        dist.destroy_process_group()


if __name__ == "__main__":
    main()
